# Info about you
name: Do Huu Dung
position: AI - Blockchain - Computer Science
email: dungdo.hust@gmail.com
company_name: VisionIn - Octan Network
company_url: https://vision-in.co.kr/
place_name: Seoul, SK

# Blog info
title: Do HD's Blog
description: Blog
url: https://dungdo123.github.io/
main_github_io: true
long_description: >-
    Hi!  Welcome to the template github.io blog site.  This can be a paragraph
    introducing yourself which will go at the top of the main page for your
    blog.

# Social links
github_url: https://github.com/dungdo123
linkedin_url: https://www.linkedin.com/in/dungdo398/
social:
  links:
    - https://www.linkedin.com/in/dungdo398/
    - https://github.com/dungdo123

# Images + files
logo: assets/img/headshot.svg
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
